build: test
	GOOS=linux go build -o go-rofi-pinboard-linux -ldflags="-s -w" ./...
	GOOS=freebsd go build -o go-rofi-pinboard-freebsd -ldflags="-s -w" ./...
	GOOS=darwin go build -o go-rofi-pinboard-macos -ldflags="-s -w" ./...

test:
	go test ./...

clean:
	rm go-rofi-pinboard-linux go-rofi-pinboard-freebsd go-rofi-pinboard-macos
